In [1]:
import pandas as pd
import numpy as np

In [2]:
adult = pd.read_csv("C:/Users/shanm/Python_Practice/Datasets/adult_with_headers.csv")
adult.shape

(32561, 15)

In [3]:
adult.head(2)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K

In [4]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [5]:
adult.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

## 1.Tasks:- 	Handle missing values as per the best practices (imputation, removal, etc.)why.

In [6]:
# Lets check for null values

adult.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

There are no null values

In [7]:
for i in adult.columns:
    print(f"{i}",adult[i].nunique())

age 73
workclass 9
fnlwgt 21648
education 16
education_num 16
marital_status 7
occupation 15
relationship 6
race 5
sex 2
capital_gain 119
capital_loss 92
hours_per_week 94
native_country 42
income 2

In [8]:
for col in adult.columns:
    print(col)
    print(adult[col].unique())
    print('-'*100)

age
[39 50 38 53 28 37 49 52 31 42 30 23 32 40 34 25 43 54 35 59 56 19 20 45
 22 48 21 24 57 44 41 29 18 47 46 36 79 27 67 33 76 17 55 61 70 64 71 68
 66 51 58 26 60 90 75 65 77 62 63 80 72 74 69 73 81 78 88 82 83 84 85 86
 87]
----------------------------------------------------------------------------------------------------
workclass
[' State-gov' ' Self-emp-not-inc' ' Private' ' Federal-gov' ' Local-gov'
 ' ?' ' Self-emp-inc' ' Without-pay' ' Never-worked']
----------------------------------------------------------------------------------------------------
fnlwgt
[ 77516  83311 215646 ...  34066  84661 257302]
----------------------------------------------------------------------------------------------------
education
[' Bachelors' ' HS-grad' ' 11th' ' Masters' ' 9th' ' Some-college'
 ' Assoc-acdm' ' Assoc-voc' ' 7th-8th' ' Doctorate' ' Prof-school'
 ' 5th-6th' ' 10th' ' 1st-4th' ' Preschool' ' 12th']
----------------------------------------------------------------------------------------------------
education_num
[13  9  7 14  5 10 12 11  4 16 15  3  6  2  1  8]
----------------------------------------------------------------------------------------------------
marital_status
[' Never-married' ' Married-civ-spouse' ' Divorced'
 ' Married-spouse-absent' ' Separated' ' Married-AF-spouse' ' Widowed']
----------------------------------------------------------------------------------------------------
occupation
[' Adm-clerical' ' Exec-managerial' ' Handlers-cleaners' ' Prof-specialty'
 ' Other-service' ' Sales' ' Craft-repair' ' Transport-moving'
 ' Farming-fishing' ' Machine-op-inspct' ' Tech-support' ' ?'
 ' Protective-serv' ' Armed-Forces' ' Priv-house-serv']
----------------------------------------------------------------------------------------------------
relationship
[' Not-in-family' ' Husband' ' Wife' ' Own-child' ' Unmarried'
 ' Other-relative']
----------------------------------------------------------------------------------------------------
race
[' White' ' Black' ' Asian-Pac-Islander' ' Amer-Indian-Eskimo' ' Other']
----------------------------------------------------------------------------------------------------
sex
[' Male' ' Female']
----------------------------------------------------------------------------------------------------
capital_gain
[ 2174     0 14084  5178  5013  2407 14344 15024  7688 34095  4064  4386
  7298  1409  3674  1055  3464  2050  2176   594 20051  6849  4101  1111
  8614  3411  2597 25236  4650  9386  2463  3103 10605  2964  3325  2580
  3471  4865 99999  6514  1471  2329  2105  2885 25124 10520  2202  2961
 27828  6767  2228  1506 13550  2635  5556  4787  3781  3137  3818  3942
   914   401  2829  2977  4934  2062  2354  5455 15020  1424  3273 22040
  4416  3908 10566   991  4931  1086  7430  6497   114  7896  2346  3418
  3432  2907  1151  2414  2290 15831 41310  4508  2538  3456  6418  1848
  3887  5721  9562  1455  2036  1831 11678  2936  2993  7443  6360  1797
  1173  4687  6723  2009  6097  2653  1639 18481  7978  2387  5060]
----------------------------------------------------------------------------------------------------
capital_loss
[   0 2042 1408 1902 1573 1887 1719 1762 1564 2179 1816 1980 1977 1876
 1340 2206 1741 1485 2339 2415 1380 1721 2051 2377 1669 2352 1672  653
 2392 1504 2001 1590 1651 1628 1848 1740 2002 1579 2258 1602  419 2547
 2174 2205 1726 2444 1138 2238  625  213 1539  880 1668 1092 1594 3004
 2231 1844  810 2824 2559 2057 1974  974 2149 1825 1735 1258 2129 2603
 2282  323 4356 2246 1617 1648 2489 3770 1755 3683 2267 2080 2457  155
 3900 2201 1944 2467 2163 2754 2472 1411]
----------------------------------------------------------------------------------------------------
hours_per_week
[40 13 16 45 50 80 30 35 60 20 52 44 15 25 38 43 55 48 58 32 70  2 22 56
 41 28 36 24 46 42 12 65  1 10 34 75 98 33 54  8  6 64 19 18 72  5  9 47
 37 21 26 14  4 59  7 99 53 39 62 57 78 90 66 11 49 84  3 17 68 27 85 31
 51 77 63 23 87 88 73 89 97 94 29 96 67 82 86 91 81 76 92 61 74 95]
----------------------------------------------------------------------------------------------------
native_country
[' United-States' ' Cuba' ' Jamaica' ' India' ' ?' ' Mexico' ' South'
 ' Puerto-Rico' ' Honduras' ' England' ' Canada' ' Germany' ' Iran'
 ' Philippines' ' Italy' ' Poland' ' Columbia' ' Cambodia' ' Thailand'
 ' Ecuador' ' Laos' ' Taiwan' ' Haiti' ' Portugal' ' Dominican-Republic'
 ' El-Salvador' ' France' ' Guatemala' ' China' ' Japan' ' Yugoslavia'
 ' Peru' ' Outlying-US(Guam-USVI-etc)' ' Scotland' ' Trinadad&Tobago'
 ' Greece' ' Nicaragua' ' Vietnam' ' Hong' ' Ireland' ' Hungary'
 ' Holand-Netherlands']
----------------------------------------------------------------------------------------------------
income
[' <=50K' ' >50K']
----------------------------------------------------------------------------------------------------

There are '?' in workclass , occupation , native_country meaning that there are missing values in dataset

In [9]:
adult.replace(' ?' ,np.nan , inplace=True)
adult.isna().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [10]:
workclass_mode = adult['workclass'].mode()[0]
occupation_mode =  adult['occupation'].mode()[0]
native_country_mode = adult['native_country'].mode()[0]
workclass_mode , occupation_mode, native_country_mode

(' Private', ' Prof-specialty', ' United-States')

In [11]:
adult.fillna({
    'workclass' : workclass_mode,
    'occupation' : occupation_mode,
    'native_country' : native_country_mode
}, inplace=True)

adult.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

Discuss the scenarios where each scaling technique is preferred and why.
- Standardization : 
  Best for algorithms sensitive to variance and normally distributed features. Example: PCA requires standardized data to correctly capture variance.Algorithms assuming Gaussian distribution (Logistic Regression, Linear Regression, LDA, PCA, SVM, Neural Networks).Preserves outliers, stabilizes variance, works well when features have different units/scales

  
- Min-Max Scaling  : 
Ideal for neural networks and clustering, where bounded ranges improve convergence. Example: KNN distance calculations are more meaningful when features are scaled.Used for distance related algorithmsRescales values to a fixed range (usually [0,1].Distance-based models (KNN, k-means, Neural Networks with bounded inputs).Ensures all features contribute equally, avoids dominance of large-scale features.

●	Apply scaling techniques to numerical features:
a.	Standard Scaling   b. Min-Max Scaling

In [12]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [13]:
ss = StandardScaler()

In [14]:
for i in adult.select_dtypes(include="number").columns:
    adult[i] = ss.fit_transform(adult[[i]])

adult.head(1)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,Male,0.148453,-0.21666,-0.035429,United-States,<=50K

# 2. Encoding Techniques:

Sex and Income are Binary columns.Lets transform binary columns first

In [15]:
from sklearn.preprocessing import LabelEncoder , OneHotEncoder

In [16]:
adult = pd.get_dummies(adult, columns=['sex', 'income'])
adult.head(1)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,0.148453,-0.21666,-0.035429,United-States,False,True,True,False

Lets transform multi-category columns

In [17]:
adult.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'capital_gain',
       'capital_loss', 'hours_per_week', 'native_country', 'sex_ Female',
       'sex_ Male', 'income_ <=50K', 'income_ >50K'],
      dtype='object')

In [18]:
le = LabelEncoder()
multicategory_col = adult.select_dtypes(include="object").columns
multicategory_col

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'native_country'],
      dtype='object')

In [19]:
for i in multicategory_col:
    adult[i] = le.fit_transform(adult[i])

adult.head(1)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,0.030671,6,-1.063611,9,1.134739,4,0,1,4,0.148453,-0.21666,-0.035429,38,False,True,True,False

In [20]:
adult.shape

(32561, 17)

In [21]:
adult.shape

(32561, 17)

●	Discuss the pros and cons of One-Hot Encoding and Label Encoding.

One-Hot Encoding (pd.get_dummies)

- Pros : 
No false ordering
Model-friendly for linear models
- Cons :
Creates many columns
Not scalable for large categories

Label Encoding

- Pros  :
Memory efficient
Simple and fast
- Cons :
Introduces artificial ranking
Can mislead some models (e.g., linear regression)

# 3. Feature Engineering:

1.Lets combine Capital_gain and Capital_loss as Total_capital.As both indicates the capital amount, combining them will give us an consolidated amount of net capital.Instead of treating gains and losses separately, this captures overall investment outcome. People with positive net capital are more likely to fall into the higher income bracket.

In [22]:
adult['Net_capital'] = adult['capital_gain'] + adult['capital_loss']
adult.head(1)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K,Net_capital
0,0.030671,6,-1.063611,9,1.134739,4,0,1,4,0.148453,-0.21666,-0.035429,38,False,True,True,False,-0.068207

2.Lets find capital activity score that says how much a person can earn in week.I added 1 to the formula as "If hours per week is 0 , 1 can balance the answer from calulating value as infinity".It is defined as Sum of capital gains and losses relative to hours worked.Measures how actively someone generates capital relative to their work hours. Could be predictive for financial status.

In [26]:
adult['capital_activity_score'] = (adult['capital_gain'] + adult['capital_loss']) / (adult['hours_per_week'] + 1)
adult.head(1)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K,Net_capital,capital_activity_score
0,0.030671,6,-1.063611,9,1.134739,4,0,1,4,0.148453,-0.21666,-0.035429,38,False,True,True,False,-0.068207,-0.070712

Lets check for skewness in data

In [28]:
adult['capital_gain'].skew()

11.953847687699787

In [31]:
adult['capital_loss'].skew()

4.594629121679697

Both capital loss and capital gain are right skewed.Log Transformation: log(x + 1) is common to handle zeros. It compresses large values while spreading out smaller ones.Since data have zeros in capital_gain and capital_loss, log transformation with a +1 shift is usually the best choice.capital_gain and capital_loss are highly right-skewed (many zeros, few large values).
Log transformation reduces the impact of extreme values and helps models like linear regression, logistic regression, or tree-based models perform better.Using np.log1p(x) ensures that zeros are handled safely (log(0+1)=0).

In [33]:
adult['capital_gain_log'] = np.log1p(adult['capital_gain'])
adult['capital_loss_log'] = np.log1p(adult['capital_loss'])
adult

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,...,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K,Net_capital,capital_activity_score,capital_gain_log,capital_loss_log
0,0.030671,6,-1.063611,9,1.134739,4,0,1,4,0.148453,...,-0.035429,38,False,True,True,False,-0.068207,-0.070712,0.138416,-0.244188
1,0.837109,5,-1.008707,9,1.134739,2,3,0,4,-0.145920,...,-2.222153,38,False,True,True,False,-0.362580,0.296673,-0.157731,-0.244188
2,-0.042642,3,0.245079,11,-0.420060,0,5,1,4,-0.145920,...,-0.035429,38,False,True,True,False,-0.362580,-0.375898,-0.157731,-0.244188
3,1.057047,3,0.425801,1,-1.197459,2,5,0,2,-0.145920,...,-0.035429,38,False,True,True,False,-0.362580,-0.375898,-0.157731,-0.244188
4,-0.775768,3,1.408176,9,1.134739,2,9,5,2,-0.145920,...,-0.035429,4,True,False,True,False,-0.362580,-0.375898,-0.157731,-0.244188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,-0.849080,3,0.639741,7,0.746039,2,12,5,4,-0.145920,...,-0.197409,38,True,False,True,False,-0.362580,-0.451762,-0.157731,-0.244188
32557,0.103983,3,-0.335433,11,-0.420060,2,6,0,4,-0.145920,...,-0.035429,38,False,True,False,True,-0.362580,-0.375898,-0.157731,-0.244188
32558,1.423610,3,-0.358777,11,-0.420060,6,0,4,4,-0.145920,...,-0.035429,38,True,False,True,False,-0.362580,-0.375898,-0.157731,-0.244188
32559,-1.215643,3,0.110960,11,-0.420060,4,0,3,4,-0.145920,...,-1.655225,38,False,True,True,False,-0.362580,0.553367,-0.157731,-0.244188
32560,0.983734,4,0.929893,11,-0.420060,2,3,5,4,1.888424,...,-0.035429,38,True,False,False,True,1.671765,1.733170,1.060711,-0.244188